[package]
name = "ard-core"
version = "0.1.0"
edition = "2024"
description = "Pure Rust Apple Remote Desktop protocol client and decoder"
license = "MIT OR Apache-2.0"

[lib]
name = "ard_rs"
path = "src/lib.rs"

[dependencies]
aes = { version = "0.8.4", default-features = false }
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"] }
getrandom = { version = "0.3.4" }
md-5 = { version = "0.10.6", default-features = false }
num-bigint = { version = "0.4.6", default-features = false, features = ["std"] }
sha1 = { version = "0.10.6", default-features = false }
sha2 = { version = "0.10.9", default-features = false }
subtle = { version = "2.6.1", default-features = false }

[dev-dependencies]
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control"] }
bytemuck = "1.25.0"
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"] }
naga = { version = "30.0.0", features = ["wgsl-in"] }
pollster = "0.4.0"
rpassword = "7.5.4"
wgpu = "30.0.0"
winit = "0.30.13"
